server:
  port: 8111
spring:
  application:
    name: hzero-boot-user


  datasource:
    url: jdbc:mysql://db.hzero.org:3306/hzero_platform?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hzero
    password: hzero


eureka:
  client:
    #向eureka注册
    register-with-eureka: true
      #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    #向哪台eureka服务端注册
    service-url:
      defaultZone: http://dev.hzero.org:8000/eureka
  instance:
    #Status显示hzero-boot-user-8111,不显示 主机名
    instance-id: hzero-boot-user-8111
    #以IP注册到注册中心
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的实际间隔，单位为秒（默认为30秒）
    lease-renewal-interval-in-seconds: 10
    #Eureka服务端收到最后一次心跳后等待时间上线，单位为秒（默认为90秒） 超时将剔除服务
    lease-expiration-duration-in-seconds: 30


mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.hzero.boot.user.domain: debug